// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfjknmnamitnwedglnmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmamtubW5hbWl0bndlZGdsbm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODEyOTYsImV4cCI6MjA2NjQ1NzI5Nn0.p4svYk5hj4WX3B7lt-8KhcUQ8uEkUuDaoybGKvgfNnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});